USE database_name;

CREATE TABLE STORAGETWO(
   ID INT AUTO_INCREMENT,
   CONSTRAINT STORAGE_PK PRIMARY KEY (ID),
   FORMAT_SUPPORTED VARCHAR(50) NOT NULL,
   STORAGE_COUNTRY VARCHAR(70),
   MAX_SIZE INT
);