USE database_name;

CREATE TABLE ITEM2(
   ID INT AUTO_INCREMENT,
   CONSTRAINT FILES_PK PRIMARY KEY (ID),
   NAME VARCHAR(40),
   DATE_CREATED DATE,
   LAST_UPDATE_DATE DATE,
   DESCRIPTION VARCHAR(40)
);